parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $scriptsDir: "@=service('App\\\\TreeManagement\\\\ScriptsDirResolver').getScriptsDir()"
    App\:
        resource: '../src/*'
        exclude: '../src/{Async,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
