baseURL: https://leektools.netlify.com/
title: Wiki de LeekTools
theme: hugo-book
defaultContentLanguage: fr

# Book configuration
disablePathToLower: true
enableGitInfo: false

params:
    BookShowToC: false
    BookMenuBundle: /menu
    BookSection: docs

languages:
    fr:
        title: Wiki de LeekTools
