baseURL: https://example.com
title: Hugo Book
theme: hugo-book
disableKinds: ["taxonomy", "taxonomyTerm"]

# Book configuration
disablePathToLower: true
enableGitInfo: true

params:
    BookShowToC: false
    BookMenuBundle: /menu
    BookSection: docs
